export const homeDetails = [
  {
    title: "Atlanta, GA1",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "1",
    height: "100%",
  },

  {
    title: "Atlanta, GA2",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "2",
    height: "50%",
  },
  {
    title: "Atlanta, GA3",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "3",
    height: "50%",
  },
  {
    title: "Atlanta, GA4",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "4",
    height: "50%",
  },
  {
    title: "Atlanta, GA5",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "5",
    height: "50%",
  },

  {
    title: "Atlanta, GA6",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "6",
    height: "100%",
  },

  {
    title: "Atlanta, GA1",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "7",
    height: "100%",
  },

  {
    title: "Atlanta, GA2",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "8",
    height: "50%",
  },
  {
    title: "Atlanta, GA3",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "9",
    height: "50%",
  },
  {
    title: "Atlanta, GA4",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "10",
    height: "50%",
  },
  {
    title: "Atlanta, GA5",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "11",
    height: "50%",
  },

  {
    title: "Atlanta, GA6",
    image: "./public/assets/atlanta.jpeg",
    buttonText: "View Homes",
    description: "",
    id: "12",
    height: "100%",
  },
];
