export const homeDetails = [
  {
    parentSlide: [
      {
        title: "New York, NY",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Explore Properties",
        description: "Luxury apartments available",
        id: "101",
        childrenhavingColumns: false,
        showViewbtn: true,
      },
      {
        title: "Los Angeles, CA",
        image: "./assets/slideimage2.jpeg",
        buttonText: "Discover",
        description: "Beachfront homes",
        id: "102",
        childrenhavingColumns: true,
        childrenhavingTwoColumns: true,
        children: [
          {
            title: "Hollywood Hills",
            image: "./assets/slideimage3.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "103",
          },
          {
            title: "Venice Beach",
            image: "./assets/slideimage4.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "104",
            showViewbtn: true,
          },
          {
            title: "Hollywood Hills11",
            image: "./assets/slideimage1.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "105",
            showViewbtn: true,
          },
          {
            title: "Venice Beach33",
            image: "./assets/slideimage2.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "106",
            showViewbtn: true,
          },
        ],
      },
      {
        title: "New York, NY",
        image: "./assets/slideimage4.jpeg",
        buttonText: "Explore Properties",
        description: "Luxury apartments available",
        id: "107",
        childrenhavingColumns: false,
        showViewbtn: true,
      },
      {
        title: "Los Angeles, CA",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Discover",
        description: "Beachfront homes",
        id: "108",
        childrenhavingColumns: true,
        childrenhavingTwoColumns: false,
        children: [
          {
            title: "Hollywood Hillsyuy",
            image: "./assets/slideimage2.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "109",
            showViewbtn: true,
          },
          {
            title: "Venice Beach666",
            image: "./assets/slideimage3.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "110",
          },
        ],
      },
    ],
  },
  {
    parentSlide: [
      {
        title: "New York, NY",
        image: "./assets/slideimage4.jpeg",
        buttonText: "Explore Properties",
        description: "Luxury apartments available",
        id: "111",
        childrenhavingColumns: false,
      },
      {
        title: "Los Angeles, CA",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Discover",
        description: "Beachfront homes",
        id: "112",
        childrenhavingColumns: true,
        childrenhavingTwoColumns: true,
        children: [
          {
            title: "Hollywood Hills",
            image: "./assets/slideimage1.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "113",
          },
          {
            title: "Venice Beach",
            image: "./assets/slideimage1.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "114",
          },
          {
            title: "Hollywood Hills11",
            image: "./assets/slideimage1.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "115",
          },
          {
            title: "Venice Beach33",
            image: "./assets/slideimage2.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "116",
          },
        ],
      },
      {
        title: "New York, NY",
        image: "./assets/slideimage3.jpeg",
        buttonText: "Explore Properties",
        description: "Luxury apartments available",
        id: "117",
        childrenhavingColumns: false,
      },
      {
        title: "Los Angeles, CA",
        image: "./assets/slideimage4.jpeg",
        buttonText: "Discover",
        description: "Beachfront homes",
        id: "118",
        childrenhavingColumns: true,
        childrenhavingTwoColumns: false,
        children: [
          {
            title: "Hollywood Hillsyuy",
            image: "./assets/slideimage2.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "119",
          },
          {
            title: "Venice Beach666",
            image: "./assets/slideimage4.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "120",
          },
        ],
      },
    ],
  },
  {
    parentSlide: [
      {
        title: "New York, NY",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Explore Properties",
        description: "Luxury apartments available",
        id: "121",
        childrenhavingColumns: false,
      },
      {
        title: "Los Angeles, CA",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Discover",
        description: "Beachfront homes",
        id: "122",
        childrenhavingColumns: true,
        childrenhavingTwoColumns: true,
        children: [
          {
            title: "Hollywood Hills",
            image: "./assets/slideimage1.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "123",
          },
          {
            title: "Venice Beach",
            image: "./assets/slideimage1.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "124",
          },
          {
            title: "Hollywood Hills11",
            image: "./assets/slideimage1.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "125",
          },
          {
            title: "Venice Beach33",
            image: "./assets/slideimage1.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "126",
          },
        ],
      },
      {
        title: "New York, NY",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Explore Properties",
        description: "Luxury apartments available",
        id: "127",
        childrenhavingColumns: false,
      },
      {
        title: "Los Angeles, CA",
        image: "./assets/slideimage1.jpeg",
        buttonText: "Discover",
        description: "Beachfront homes",
        id: "128",
        childrenhavingColumns: true,
        childrenhavingTwoColumns: false,
        children: [
          {
            title: "Hollywood Hillsyuy",
            image: "./assets/slideimage3.jpeg",
            buttonText: "View More",
            description: "Modern luxury",
            id: "129",
          },
          {
            title: "Venice Beach666",
            image: "./assets/slideimage4.jpeg",
            buttonText: "See Homes",
            description: "Oceanfront living",
            id: "130",
          },
        ],
      },
    ],
  },
];
